const pages={overview:'Overview',profile:'My Bound Profile',servers:'Servers',safety:'Safety & Consent',moderation:'Moderation',tickets:'Tickets & Support',economy:'Economy',staff:'Staff',roleplay:'Social & RP',logs:'Audit Log',settings:'Server Settings'};
const generic={profile:['My Bound Profile','Manage your Bound identity, ownership connections and privacy controls.',[['♡','Connections','Owners, subs and relationship state'],['◉','Visibility','Choose what your profile displays'],['◆','Privacy','Data controls and deletion requests']]],servers:['Servers','Choose a Discord server to configure with Bound.',[['◇','The Dark Side','12,842 members'],['◇','Buds and Butts','4,104 members'],['＋','Add a server','Invite Bound to another community']]],moderation:['Moderation','Fast staff controls, member actions and isolation workflows.',[['⌁','Actions','Ban, mute, jail and user information'],['◆','Containment','Cage and safeword workflows'],['≣','History','Auditable moderation actions']]],tickets:['Tickets & Support','Configure ticket panels, transcripts, ratings and staff claims.',[['▱','17 open','6 awaiting staff'],['★','4.8 rating','Past 30 days'],['♙','Staff stats','Claims, closes and ratings']]],staff:['Staff','Manage roles, assignments, clock-ins, breaks and weekly performance.',[['♙','24 clocked in','Active right now'],['◷','6 on break','Approved breaks'],['◇','Assignments','Roles and temporary duties']]],roleplay:['Social & RP','Control roleplay interactions, consent defaults and social features.',[['♡','Interactions','Hug, kiss, bite, cuddle and more'],['◉','Ownership','Claims, owners and subs'],['◇','Gag system','Consent-based gag controls']]],logs:['Audit Log','Search what Bound and your staff have changed across the server.',[['≣','Moderation','Actions and reasons'],['₦','Economy','Balance adjustments and rewards'],['◆','Safety','Protected review history']]]};

const activity=[['◆','Safety flag opened','@ash submitted a new safety flag','2m'],['▱','Ticket claimed','@luna claimed ticket #1048','6m'],['₦','Large heist completed','@raven won 42,500 Nugs','11m'],['♙','Staff clocked in','@kira joined the staff shift','18m'],['◇','Member verified','@nova completed verification','21m']];
const activityList=document.getElementById('activityList');
activityList.innerHTML=activity.map(x=>`<div class="activity-item"><span class="activity-icon">${x[0]}</span><div><b>${x[1]}</b><small>${x[2]}</small></div><small>${x[3]}</small></div>`).join('');
document.getElementById('uptimeBars').innerHTML=Array.from({length:36},()=>'<i></i>').join('');

function buildGeneric(key){const v=generic[key];if(!v)return;const el=document.getElementById(`view-${key}`);if(el.dataset.ready)return;el.innerHTML=`<div class="generic-card"><span class="eyebrow">BOUND CONTROL CENTRE</span><h2>${v[0]}</h2><p>${v[1]}</p><div class="generic-feature-grid">${v[2].map(f=>`<div class="generic-feature"><span>${f[0]}</span><b>${f[1]}</b><small>${f[2]}</small></div>`).join('')}</div></div>`;el.dataset.ready='1';}
function showView(key){if(generic[key])buildGeneric(key);document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(`view-${key}`)?.classList.add('active');document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===key));document.getElementById('pageTitle').textContent=pages[key]||'Dashboard';document.getElementById('sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
document.querySelectorAll('[data-jump]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.jump)));
document.getElementById('menuBtn').addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));
document.querySelectorAll('.switch').forEach(s=>s.addEventListener('click',()=>{s.classList.toggle('on');const state=document.getElementById('saveState');if(state)state.textContent='Unsaved changes';}));
function toast(title='Saved',message='Your changes were saved.'){const t=document.getElementById('toast');t.querySelector('b').textContent=title;t.querySelector('small').textContent=message;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2600)}
document.getElementById('saveSettings')?.addEventListener('click',()=>{document.getElementById('saveState').textContent='All changes saved';toast('Server settings saved','Your Bound configuration is up to date.')});
document.getElementById('saveEconomy')?.addEventListener('click',()=>toast('Economy settings saved','Nugs configuration has been updated.'));
