(() => {
  const supportUrl='https://discord.gg/NVseqMDNRd';
  const openDiscord=(copy='Open Bound Society')=>`<div class="finish-actions"><a class="finish-btn primary" href="${supportUrl}" target="_blank" rel="noopener noreferrer">${copy} ↗</a></div>`;
  const pages={
    servers:{
      kicker:'BOUND NETWORK',title:'Your servers, one control centre.',copy:'Switch between communities you manage, see whether Bound is installed, and understand what each server has unlocked.',pills:['Discord verified','Permission checked','Faction aware'],
      body:`<div class="finish-grid"><article class="finish-card"><span class="finish-state">LIVE</span><div class="finish-icon">◇</div><small>SERVER ACCESS</small><h3>Permission-aware switching</h3><p>Only servers Discord says you own or can manage appear in your dashboard picker.</p></article><article class="finish-card"><span class="finish-state">SYNCED</span><div class="finish-icon">B</div><small>BOUND STATUS</small><h3>Installation detection</h3><p>Bound activation and server configuration are checked before controls are exposed.</p></article><article class="finish-card"><span class="finish-state locked">OWNER</span><div class="finish-icon">₦</div><small>FACTION ACCESS</small><h3>Approval protected</h3><p>Faction features stay locked until that server has been approved for the Bound faction network.</p></article></div><div class="finish-banner"><div><span class="finish-kicker">SERVER PICKER</span><h3>Use the server selector in the sidebar</h3><p>Every dashboard module follows the currently selected server, so you never have to re-enter IDs or open a separate setup page.</p></div><div class="finish-progress"><i class="on"></i><i class="on"></i><i class="on"></i><i class="on"></i><i></i></div></div>`
    },
    moderation:{
      kicker:'BOUND MODERATION',title:'Control without clutter.',copy:'The dashboard reflects the moderation stack while sensitive enforcement remains protected by Discord permissions and server-side checks.',pills:['Case history','Custom notices','Jail workflows','Protected actions'],
      body:`<div class="finish-grid"><article class="finish-card wide"><span class="finish-state">DISCORD CONTROL</span><div class="finish-icon">⌁</div><small>MODERATION CENTRE</small><h3>Cases, warnings and actions</h3><p>Use Bound moderation commands in Discord for warnings, mutes, kicks, bans, jail and case lookups. Dashboard actions stay read-safe until the full permission matrix is enabled.</p><div class="finish-list"><div><i>!</i><span><b>tds caselist @user</b><span>Review that user's server-scoped moderation history</span></span><em>READY</em></div><div><i>✉</i><span><b>/moderation-panel</b><span>Configure the DM wording users receive for moderation actions</span></span><em>LIVE</em></div><div><i>▣</i><span><b>Jail & containment</b><span>Server-specific moderation and private isolation workflows</span></span><em>LOCKED</em></div></div></article><article class="finish-card"><span class="finish-state">PROTECTED</span><div class="finish-icon">◆</div><small>SAFETY LAYER</small><h3>Every action is checked</h3><p>Guild permission is revalidated before server data can be changed, with protected audit paths and no client-side service secrets.</p></article></div><div class="finish-security"><i></i> Write actions are permission checked server-side before Supabase is touched.</div>`
    },
    tickets:{
      kicker:'SUPPORT OPERATIONS',title:'Tickets that feel like a real helpdesk.',copy:'Bound ties together ticket creation, claims, transcripts, ratings and staff performance without making your team jump between systems.',pills:['Claims','Transcripts','Ratings','Verification','Terminate'],
      body:`<div class="finish-grid"><article class="finish-card"><span class="finish-state">LIVE</span><div class="finish-icon">▱</div><small>TICKET FLOW</small><h3>Support & verification</h3><p>Multiple ticket panels can use different questions, roles and workflows while still feeding the same staff system.</p></article><article class="finish-card"><span class="finish-state">TRACKED</span><div class="finish-icon">★</div><small>FEEDBACK</small><h3>Post-close ratings</h3><p>Users can rate staff after closure so weekly performance data reflects actual support quality.</p></article><article class="finish-card"><span class="finish-state">MANAGE MESSAGES</span><div class="finish-icon">×</div><small>TERMINATE</small><h3>Hard close when needed</h3><p>Terminate is deliberately separate from normal close permissions and can be used by members with Manage Messages.</p></article></div><div class="finish-banner"><div><span class="finish-kicker">SAFE CLOSURE</span><h3>Close keeps the record. Terminate removes the ticket.</h3><p>Normal closure preserves transcript/rating flows. Termination is for cases that should end immediately without the normal post-close experience.</p></div><div class="finish-progress"><i class="on"></i><i class="on"></i><i class="on"></i><i class="on"></i><i class="on"></i></div></div>`
    },
    staff:{
      kicker:'STAFF HQ',title:'Give your staff an actual operating system.',copy:'Clocking, breaks, temporary access and assignments can all live inside the same private Bound setup.',pills:['Clock in/out','Break approval','Assignments','Weekly stats'],
      body:`<div class="finish-grid"><article class="finish-card wide"><span class="finish-state">PRIVATE BUILD</span><div class="finish-icon">♙</div><small>STAFF OPERATIONS</small><h3>Everything required for a staff shift</h3><p>Staff can clock in, receive their active role, request breaks, be assigned jobs and automatically lose temporary access after the configured shift window.</p><div class="finish-list"><div><i>◷</i><span><b>Clocking</b><span>Tracks active shifts and grants the configured staff role</span></span><em>AUTO</em></div><div><i>☕</i><span><b>Breaks</b><span>Approval flow with staff notifications</span></span><em>CONTROLLED</em></div><div><i>◇</i><span><b>Assignments</b><span>Temporary jobs and role-based duties</span></span><em>SYNCED</em></div><div><i>≣</i><span><b>Performance</b><span>Ticket claims, closes and ratings feed weekly stats</span></span><em>TRACKED</em></div></div></article><article class="finish-card"><span class="finish-state">PREMIUM</span><div class="finish-icon">✦</div><small>CUSTOM BUILDS</small><h3>Your workflow can be different</h3><p>Private Bound systems can be shaped around the staff structure your server already uses instead of forcing a generic template.</p>${openDiscord('Ask about custom staff tools')}</article></div>`
    },
    logs:{
      kicker:'AUDIT & ACTIVITY',title:'Know what changed and why.',copy:'The dashboard keeps activity readable while moderation, faction, safety and staff systems retain their own deeper server-side records.',pills:['Server scoped','Reasons','Actor tracking','Protected data'],
      body:`<div class="finish-table"><div class="finish-row header"><span>Activity</span><span>Source</span><span>Access</span><span>Status</span></div><div class="finish-row"><b>Moderation cases</b><span>Bound moderation</span><span>Manage Server</span><span>Tracked</span></div><div class="finish-row"><b>Safety review</b><span>Safety system</span><span>Protected</span><span>Tracked</span></div><div class="finish-row"><b>Faction activity</b><span>Faction / Nugs</span><span>Approved server</span><span>Synced</span></div><div class="finish-row"><b>Staff performance</b><span>Tickets / staff</span><span>Private build</span><span>Tracked</span></div></div><div class="finish-banner"><div><span class="finish-kicker">FULL SEARCH</span><h3>Detailed audit search stays protected</h3><p>Overview shows recent activity now. Full cross-system search can be enabled as each permission table is connected to the dashboard.</p></div><div class="finish-progress"><i class="on"></i><i class="on"></i><i class="on"></i><i></i><i></i></div></div>`
    }
  };

  function render(key){
    const def=pages[key],el=document.getElementById(`view-${key}`);
    if(!def||!el||el.dataset.finished==='1')return;
    el.innerHTML=`<div class="finish-shell"><section class="finish-hero"><span class="finish-kicker">${def.kicker}</span><h2>${def.title}</h2><p>${def.copy}</p><div class="finish-pills">${def.pills.map(x=>`<span>${x}</span>`).join('')}</div></section>${def.body}</div>`;
    el.dataset.finished='1';
  }

  function arm(){
    Object.keys(pages).forEach(k=>render(k));
    document.querySelectorAll('.nav-item[data-view]').forEach(btn=>btn.addEventListener('click',()=>{const k=btn.dataset.view;if(pages[k])render(k)}));
    const overview=document.getElementById('view-overview');
    if(overview&&!document.getElementById('finishTrustStrip')){
      overview.insertAdjacentHTML('beforeend',`<div class="finish-banner" id="finishTrustStrip" style="margin-top:12px"><div><span class="finish-kicker">BUILT TO STAY CONNECTED</span><h3>Discord identity. Supabase data. Bound permissions.</h3><p>The control centre rechecks server access, retries safe reads when connections wobble, and keeps write actions protected behind server-side validation.</p></div><div class="finish-security"><i></i> Connection protected</div></div>`);
    }
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',arm);else arm();
})();