create table if not exists public.faction_treasury_deposits (
  id bigint generated by default as identity primary key,
  faction_id text not null references public.factions(faction_id) on delete cascade,
  user_id text not null,
  amount bigint not null check (amount > 0),
  user_balance_after bigint not null check (user_balance_after >= 0),
  faction_balance_after bigint not null check (faction_balance_after >= 0),
  source text not null default 'dashboard' check (source in ('dashboard', 'discord')),
  created_at timestamptz not null default now()
);

create index if not exists faction_treasury_deposits_faction_created_idx
  on public.faction_treasury_deposits (faction_id, created_at desc);
create index if not exists faction_treasury_deposits_user_created_idx
  on public.faction_treasury_deposits (user_id, created_at desc);

alter table public.faction_treasury_deposits enable row level security;
revoke all on table public.faction_treasury_deposits from public, anon, authenticated;
grant select, insert on table public.faction_treasury_deposits to service_role;
grant usage, select on sequence public.faction_treasury_deposits_id_seq to service_role;

comment on table public.faction_treasury_deposits is
  'Audited 1:1 transfers from a user global balance into their faction treasury.';

create or replace function public.dashboard_deposit_to_faction(
  p_user_id text,
  p_faction_id text,
  p_amount bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role text;
  v_user_balance bigint;
  v_faction_balance bigint;
begin
  p_user_id := trim(coalesce(p_user_id, ''));
  p_faction_id := trim(coalesce(p_faction_id, ''));
  p_amount := coalesce(p_amount, 0);

  if p_user_id = '' or p_faction_id = '' or p_amount <= 0 or p_amount > 1000000000 then
    return jsonb_build_object('success', false, 'error', 'INVALID_DEPOSIT', 'message', 'Enter a valid deposit amount.');
  end if;

  select fm.faction_role into v_role
  from public.faction_members fm
  where fm.user_id = p_user_id and fm.faction_id = p_faction_id;

  if v_role is distinct from 'leader' then
    return jsonb_build_object('success', false, 'error', 'LEADER_REQUIRED', 'message', 'Only the faction leader can deposit through the dashboard.');
  end if;

  perform pg_advisory_xact_lock(hashtext(p_faction_id));

  select ub.money into v_user_balance
  from public.user_balances ub
  where ub.user_id = p_user_id
  for update;

  if not found or v_user_balance < p_amount then
    return jsonb_build_object('success', false, 'error', 'INSUFFICIENT_BALANCE', 'message', 'Your global balance is too low for that deposit.');
  end if;

  select f.money into v_faction_balance
  from public.factions f
  where f.faction_id = p_faction_id
  for update;

  if not found then
    return jsonb_build_object('success', false, 'error', 'FACTION_NOT_FOUND', 'message', 'The faction no longer exists.');
  end if;

  v_user_balance := v_user_balance - p_amount;
  v_faction_balance := v_faction_balance + p_amount;

  update public.user_balances
  set money = v_user_balance, updated_at = now()
  where user_id = p_user_id;

  update public.factions
  set money = v_faction_balance, updated_at = now()
  where faction_id = p_faction_id;

  insert into public.faction_treasury_deposits
    (faction_id, user_id, amount, user_balance_after, faction_balance_after)
  values
    (p_faction_id, p_user_id, p_amount, v_user_balance, v_faction_balance);

  return jsonb_build_object(
    'success', true,
    'amount', p_amount,
    'user_balance', v_user_balance,
    'faction_balance', v_faction_balance
  );
end;
$$;

revoke execute on function public.dashboard_deposit_to_faction(text, text, bigint) from public, anon, authenticated;
grant execute on function public.dashboard_deposit_to_faction(text, text, bigint) to service_role;

